---
language: lisp

env:
  matrix:
  - LISP=sbcl
  # - LISP=sbcl32
  # - LISP=ccl
  # - LISP=ccl32
  # - LISP=ecl
  # - LISP=clisp
  # - LISP=clisp32
  # - LISP=allegro
  # - LISP=cmucl
  # - LISP=abcl

before_install:
- sudo apt-get update

install:
- curl -L https://raw.githubusercontent.com/wobh/xlisp/xlisp-93-test-travis-install-script/lib/travis/install.sh | sh

script:
- bin/fetch-configlet
- bin/configlet .
- cl -f 'bin/xlisp-test.lisp' -e '(xlisp-test:travis-build)'

# Cut and paste above to run all tests locally.

# Add a numeric argument to XLISP-TEST:RUN-TESTS-ALL between 0 and 7
# to control optional verbosity (default is 2).
