---
language: lisp

env:
  matrix:
  - LISP=sbcl
  # - LISP=sbcl32
  # - LISP=ccl
  # - LISP=ccl32
  # - LISP=ecl
  # - LISP=clisp
  # - LISP=clisp32
  # - LISP=allegro
  # - LISP=cmucl

matrix:
  allow_failures:
  - LISP=abcl

before_install:
- sudo apt-get update
- curl -L https://raw.github.com/KeenS/CIM/master/scripts/cim_installer | sh
- CIM_HOME="${HOME}/.cim"
- export CIM_HOME
- PATH="$CIM_HOME/bin:$PATH";export PATH
- CIM_ID="$$";export CIM_ID
- curl -o "${CIM_HOME}" -L http://beta.quicklisp.org/quicklisp.lisp
- cl -f quicklisp.lisp -e '(quicklisp-quickstart:install)'

install:
- curl -L https://raw.githubusercontent.com/wobh/xlisp/xlisp-93-test-travis-install-script/lib/travis/install.sh | sh
#- curl -L https://github.com/exercism/xlisp/lib/travis/raw/master/install.sh | sh

script:
- bin/fetch-configlet
- bin/configlet .
- cl -f 'bin/xlisp-test.lisp' -e '(xlisp-test:travis-build)'

# Cut and paste above to run all tests locally.

# Add a numeric argument to XLISP-TEST:RUN-TESTS-ALL between 0 and 7
# to control optional verbosity (default is 2).
